import { useParams, useNavigate } from "react-router";
import { useGetHotelByIdQuery, useCreateBookingMutation } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Calendar, Users, MapPin, Star, Shield, CreditCard, ArrowLeft, CheckCircle2, Sparkles, Loader2 } from "lucide-react";
import StripeEmbeddedCheckout from "@/components/StripeEmbeddedCheckout";

function HotelBookingPage() {
  const { _id } = useParams();
  const navigate = useNavigate();
  const { data: hotel, isLoading, isError, error } = useGetHotelByIdQuery(_id);
  const [createBooking, { isLoading: isCreating }] = useCreateBookingMutation();
  const [formData, setFormData] = useState({
    checkIn: "",
    checkOut: "",
    guestCount: 1,
    specialRequests: ""
  });
  const [showCheckout, setShowCheckout] = useState(false);
  const [clientSecret, setClientSecret] = useState(null);
  const [bookingId, setBookingId] = useState(null);
  const [sessionId, setSessionId] = useState(null);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const calculateTotalPrice = () => {
    if (!formData.checkIn || !formData.checkOut || !hotel?.price) return 0;
    const checkInDate = new Date(formData.checkIn);
    const checkOutDate = new Date(formData.checkOut);
    const nights = Math.ceil((checkOutDate.getTime() - checkInDate.getTime()) / (1000 * 60 * 60 * 24));
    return nights * hotel.price;
  };

  const validateForm = () => {
    const today = new Date().toISOString().split('T')[0];
    
    if (!formData.checkIn) {
      toast.error("Please select check-in date");
      return false;
    }
    
    if (formData.checkIn < today) {
      toast.error("Check-in date cannot be in the past");
      return false;
    }
    
    if (!formData.checkOut) {
      toast.error("Please select check-out date");
      return false;
    }
    
    if (formData.checkOut <= formData.checkIn) {
      toast.error("Check-out date must be after check-in date");
      return false;
    }
    
    if (formData.guestCount < 1 || formData.guestCount > 10) {
      toast.error("Guest count must be between 1 and 10");
      return false;
    }
    
    return true;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) return;
    
    try {
      const bookingData = {
        hotelId: _id,
        checkIn: formData.checkIn,
        checkOut: formData.checkOut,
        // roomNumber is auto-generated by the backend
        guestCount: Number(formData.guestCount),
        specialRequests: formData.specialRequests
      };
      
      const result = await createBooking(bookingData).unwrap();
      
      // Show embedded checkout if clientSecret is available
      if (result.clientSecret) {
        setClientSecret(result.clientSecret);
        setBookingId(result.bookingId);
        setSessionId(result.sessionId);
        setShowCheckout(true);
        toast.success("Please complete payment to confirm your booking");
      } else {
        const errorMsg = "Payment session not available. Please try again.";
        toast.error(errorMsg);
      }
    } catch (err) {
      toast.error(err?.data?.message || "Failed to create booking");
    }
  };

  const handlePaymentSuccess = () => {
    // Navigate to confirmation page - the webhook will update the booking status
    // Use sessionId for retrieving booking details
    if (sessionId) {
      navigate(`/booking-confirmation?session_id=${sessionId}`);
    } else if (bookingId) {
      navigate(`/booking-confirmation?session_id=${bookingId}`);
    }
  };

  const handlePaymentCancel = () => {
    setShowCheckout(false);
    setClientSecret(null);
    setBookingId(null);
    setSessionId(null);
    toast.info("Payment cancelled. You can try again.");
  };

  if (isLoading) {
    return (
      <main className="px-4 py-6">
        <Skeleton className="h-10 w-64 mb-4" />
        <Skeleton className="h-64 w-full" />
      </main>
    );
  }

  if (isError) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center">
        <h2 className="text-2xl font-bold text-destructive mb-4">Error Loading Hotel</h2>
        <p className="text-muted-foreground">{error?.data?.message || "Something went wrong."}</p>
      </div>
    );
  }

  // If checkout is shown, display only the payment form
  if (showCheckout && clientSecret) {
    const nights = Math.ceil(
      (new Date(formData.checkOut).getTime() - new Date(formData.checkIn).getTime()) / 
      (1000 * 60 * 60 * 24)
    );
    
    return (
      <main className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 max-w-6xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            {/* Header */}
            <div className="mb-6">
              <Button
                variant="ghost"
                onClick={handlePaymentCancel}
                className="mb-4"
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Booking Details
              </Button>
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <CreditCard className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <h1 className="text-3xl md:text-4xl font-bold font-serif">Complete Your Payment</h1>
                  <p className="text-muted-foreground mt-1">Secure checkout powered by Stripe</p>
                </div>
              </div>
            </div>

            <div className="grid lg:grid-cols-3 gap-6">
              {/* Booking Summary Sidebar */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2 }}
                className="lg:col-span-1"
              >
                <Card className="sticky top-4">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <CheckCircle2 className="w-5 h-5 text-primary" />
                      Booking Summary
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {/* Hotel Info */}
                    <div className="space-y-3">
                      <div className="relative w-full h-32 rounded-lg overflow-hidden">
                        <img 
                          src={hotel.image} 
                          alt={hotel.name} 
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div>
                        <h3 className="font-semibold text-lg">{hotel.name}</h3>
                        <div className="flex items-center gap-1 text-sm text-muted-foreground mt-1">
                          <MapPin className="w-4 h-4" />
                          {hotel.location}
                        </div>
                        {hotel.rating && (
                          <div className="flex items-center gap-1 mt-2">
                            <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                            <span className="text-sm font-medium">{hotel.rating}</span>
                          </div>
                        )}
                      </div>
                    </div>

                    <div className="border-t pt-4 space-y-3">
                      <div className="flex items-center gap-2 text-sm">
                        <Calendar className="w-4 h-4 text-muted-foreground" />
                        <div className="flex-1">
                          <div className="font-medium">Check-in</div>
                          <div className="text-muted-foreground">
                            {new Date(formData.checkIn).toLocaleDateString('en-US', { 
                              weekday: 'short', 
                              month: 'short', 
                              day: 'numeric' 
                            })}
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Calendar className="w-4 h-4 text-muted-foreground" />
                        <div className="flex-1">
                          <div className="font-medium">Check-out</div>
                          <div className="text-muted-foreground">
                            {new Date(formData.checkOut).toLocaleDateString('en-US', { 
                              weekday: 'short', 
                              month: 'short', 
                              day: 'numeric' 
                            })}
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Users className="w-4 h-4 text-muted-foreground" />
                        <div className="flex-1">
                          <div className="font-medium">Guests</div>
                          <div className="text-muted-foreground">{formData.guestCount} {formData.guestCount === 1 ? 'guest' : 'guests'}</div>
                        </div>
                      </div>
                    </div>

                    <div className="border-t pt-4 space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-muted-foreground">${hotel.price || 100} × {nights} {nights === 1 ? 'night' : 'nights'}</span>
                        <span>${(hotel.price || 100) * nights}</span>
                      </div>
                      <div className="flex justify-between text-lg font-bold pt-2 border-t">
                        <span>Total</span>
                        <span className="text-primary">${calculateTotalPrice()}</span>
                      </div>
                    </div>

                    <div className="pt-4 border-t">
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <Shield className="w-4 h-4" />
                        <span>Your payment is secure and encrypted</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>

              {/* Payment Form */}
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 }}
                className="lg:col-span-2"
              >
                <StripeEmbeddedCheckout
                  clientSecret={clientSecret}
                  onSuccess={handlePaymentSuccess}
                  onCancel={handlePaymentCancel}
                  bookingDetails={{
                    totalPrice: calculateTotalPrice(),
                    nights: nights,
                    pricePerNight: hotel.price || 100,
                  }}
                />
              </motion.div>
            </div>
          </motion.div>
        </div>
      </main>
    );
  }

  const nights = formData.checkIn && formData.checkOut 
    ? Math.ceil((new Date(formData.checkOut).getTime() - new Date(formData.checkIn).getTime()) / (1000 * 60 * 60 * 24))
    : 0;

  return (
    <main className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 max-w-7xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          {/* Header */}
          <div className="mb-8">
            <Button
              variant="ghost"
              onClick={() => navigate(-1)}
              className="mb-4"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
            <h1 className="text-4xl md:text-5xl font-bold font-serif mb-2">Book Your Stay</h1>
            <p className="text-lg text-muted-foreground">Complete your reservation in just a few steps</p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Hotel Information */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.1 }}
              className="lg:col-span-2 space-y-6"
            >
              <Card>
                <div className="relative w-full h-64 md:h-96 rounded-t-lg overflow-hidden">
                  <img 
                    src={hotel.image} 
                    alt={hotel.name} 
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute top-4 right-4">
                    <Badge className="bg-black/50 text-white backdrop-blur-sm">
                      <Star className="w-3 h-3 mr-1 fill-yellow-400 text-yellow-400" />
                      {hotel.rating || "New"}
                    </Badge>
                  </div>
                </div>
                <CardContent className="p-6">
                  <h2 className="text-2xl md:text-3xl font-bold font-serif mb-2">{hotel.name}</h2>
                  <div className="flex items-center gap-2 text-muted-foreground mb-4">
                    <MapPin className="w-4 h-4" />
                    <span>{hotel.location}</span>
                  </div>
                  <p className="text-muted-foreground leading-relaxed mb-6">{hotel.description}</p>
                  
                  {hotel.amenities && hotel.amenities.length > 0 && (
                    <div className="border-t pt-4">
                      <h3 className="font-semibold mb-3">Amenities</h3>
                      <div className="flex flex-wrap gap-2">
                        {hotel.amenities.slice(0, 6).map((amenity, index) => (
                          <Badge key={index} variant="secondary">
                            {amenity}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </motion.div>

            {/* Booking Form */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 }}
              className="lg:col-span-1"
            >
              <Card className="sticky top-4">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-primary" />
                    Reservation Details
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <form onSubmit={handleSubmit} className="space-y-5">
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="checkIn" className="flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          Check-in
                        </Label>
                        <Input 
                          id="checkIn" 
                          name="checkIn" 
                          type="date" 
                          value={formData.checkIn}
                          onChange={handleInputChange}
                          min={new Date().toISOString().split('T')[0]}
                          className="h-11"
                          required 
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="checkOut" className="flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          Check-out
                        </Label>
                        <Input 
                          id="checkOut" 
                          name="checkOut" 
                          type="date" 
                          value={formData.checkOut}
                          onChange={handleInputChange}
                          min={formData.checkIn || new Date().toISOString().split('T')[0]}
                          className="h-11"
                          required 
                        />
                      </div>
                    </div>
                    
                    <div className="space-y-2">
                      <Label htmlFor="guestCount" className="flex items-center gap-2">
                        <Users className="w-4 h-4" />
                        Number of Guests
                      </Label>
                      <Input 
                        id="guestCount" 
                        name="guestCount" 
                        type="number" 
                        min="1" 
                        max="10"
                        value={formData.guestCount}
                        onChange={handleInputChange}
                        className="h-11"
                        required 
                      />
                    </div>
                    
                    <div className="space-y-2">
                      <Label htmlFor="specialRequests">Special Requests (Optional)</Label>
                      <Textarea 
                        id="specialRequests" 
                        name="specialRequests" 
                        value={formData.specialRequests}
                        onChange={handleInputChange}
                        placeholder="Any special requests or notes..."
                        maxLength={500}
                        rows={3}
                        className="resize-none"
                      />
                      <p className="text-xs text-muted-foreground">
                        {formData.specialRequests.length}/500 characters
                      </p>
                    </div>
                    
                    {calculateTotalPrice() > 0 && (
                      <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="p-5 bg-gradient-to-br from-primary/10 to-primary/5 rounded-lg border border-primary/20"
                      >
                        <div className="space-y-2">
                          <div className="flex justify-between text-sm">
                            <span className="text-muted-foreground">${hotel.price || 100} × {nights} {nights === 1 ? 'night' : 'nights'}</span>
                            <span>${(hotel.price || 100) * nights}</span>
                          </div>
                          <div className="flex justify-between items-center pt-2 border-t">
                            <span className="font-semibold">Total</span>
                            <span className="text-2xl font-bold text-primary">${calculateTotalPrice()}</span>
                          </div>
                        </div>
                      </motion.div>
                    )}
                    
                    <Button 
                      type="submit" 
                      disabled={isCreating || !formData.checkIn || !formData.checkOut} 
                      className="w-full h-12 text-base font-semibold"
                      size="lg"
                    >
                      {isCreating ? (
                        <>
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                          Processing...
                        </>
                      ) : (
                        <>
                          <CreditCard className="w-4 h-4 mr-2" />
                          Proceed to Payment
                        </>
                      )}
                    </Button>

                    <div className="flex items-center gap-2 text-xs text-muted-foreground justify-center pt-2">
                      <Shield className="w-4 h-4" />
                      <span>Secure payment powered by Stripe</span>
                    </div>
                  </form>
                </CardContent>
              </Card>
            </motion.div>
          </div>
        </motion.div>
      </div>
    </main>
  );
}

export default HotelBookingPage;


